

// Unified Mock Data with Dynamic Colors
export const tasksMockData = [
  {
    id: 'item-001',
    title: 'Project Kickoff',
    description: 'Cabling for Network Refresh Project Proposal RFP#: TS-9th-HS14-Y25',
    startDate: '2024-12-01T09:00:00',
    endDate: '2024-12-03T17:00:00',
    status: 'In Progress',
    progress: '10.00%',
    publishedBy: 'Admin Role',
    category: 'Event',
    priority: 'Medium',
    contact: 'Electrical Contractor',
    email: 'Tim.Pietrzak@yahoo.com',
    phone: '000-000-0000',
    address: '23 bethel avenue, Anna Nagar, Anna Nagar 3rd Main Rd, VGP Selva Nagar, Velachery, Chennai, Tamil Nadu 600042',
    notes: 'Testing from postman note',
  },
  {
    id: 'item-002',
    title: 'Design Sprint',
    description: 'Network Infrastructure Upgrade Proposal RFP#: TX-5678-Y2022',
    startDate: '2024-12-05T11:00:00',
    endDate: '2024-12-09T18:00:00',
    status: 'Not Started',
    progress: '5.00%',
    publishedBy: 'Manager Role',
    category: 'Event',
    priority: 'Medium',
    contact: 'Network Architect',
    email: 'contact@networkarchitect.com',
    phone: '123-456-7890',
    address: '123 Network St, City, State, 12345, United States',
    notes: 'Design phase awaiting approval',
  },
  {
    id: 'item-003',
    title: 'Development Phase',
    description: 'Server Upgrade Proposal RFP#: TX-1011-Y2022',
    startDate: '2024-12-11T08:00:00',
    endDate: '2024-12-14T18:00:00',
    status: 'Completed',
    progress: '100.00%',
    publishedBy: 'Admin Role',
    category: 'Task',
    priority: 'High',
    contact: 'Development Team',
    email: 'devteam@company.com',
    phone: '000-111-2222',
    address: '456 Dev Rd, City, State, 67890, United States',
    notes: 'All tasks completed successfully',
  },
  {
    id: 'item-004',
    title: 'Testing Phase',
    description: 'Cabling for New School Project RFP#: TX-2323-Y2022',
    startDate: '2024-12-15T11:00:00',
    endDate: '2024-12-17T17:00:00',
    status: 'In Progress',
    progress: '30.00%',
    publishedBy: 'Team Lead',
    category: 'Task',
    priority: 'Medium',
    contact: 'Testing Coordinator',
    email: 'testing@company.com',
    phone: '333-444-5555',
    address: '789 Test Ave, City, State, 11223, United States',
    notes: 'Awaiting additional equipment',
  },
  {
    id: 'item-005',
    title: 'Client Meeting',
    description: 'Fiber Optic Installation RFP#: TX-4567-Y2022',
    startDate: '2024-12-18T11:00:00',
    endDate: '2024-12-20T16:00:00',
    status: 'Overdue',
    progress: '50.00%',
    publishedBy: 'Project Coordinator',
    category: 'Task',
    priority: 'Low',
    contact: 'Client Representative',
    email: 'client@company.com',
    phone: '666-777-8888',
    address: '123 Client St, City, State, 44556, United States',
    notes: 'Meeting postponed, needs rescheduling',
  },
  {
    id: 'item-006',
    title: 'Feedback Session',
    description: 'WiFi Expansion Proposal RFP#: TX-7890-Y2022',
    startDate: '2024-12-21T14:00:00',
    endDate: '2024-12-23T17:00:00',
    status: 'Completed',
    progress: '100.00%',
    publishedBy: 'Admin Role',
    category: 'Event',
    priority: 'Medium',
    contact: 'WiFi Engineer',
    email: 'wifi.engineer@company.com',
    phone: '999-000-1111',
    address: '555 WiFi Blvd, City, State, 33445, United States',
    notes: 'Feedback received, all good',
  },
  {
    id: 'item-007',
    title: 'Retrospective',
    description: 'VoIP Setup RFP#: TX-1112-Y2022',
    startDate: '2024-12-24T09:00:00',
    endDate: '2024-12-26T12:00:00',
    status: 'In Progress',
    progress: '75.00%',
    publishedBy: 'Team Lead',
    category: 'Event',
    priority: 'High',
    contact: 'VoIP Specialist',
    email: 'voip.specialist@company.com',
    phone: '222-333-4444',
    address: '101 VoIP St, City, State, 66778, United States',
    notes: 'Waiting for final approval',
  },
  {
    id: 'item-008',
    title: 'Planning Meeting',
    description: 'IT Hardware Replacement Proposal RFP#: TX-1314-Y2022',
    startDate: '2024-12-27T11:00:00',
    endDate: '2024-12-29T14:00:00',
    status: 'In Progress',
    progress: '60.00%',
    publishedBy: 'Admin Role',
    category: 'Task',
    priority: 'Medium',
    contact: 'IT Manager',
    email: 'it.manager@company.com',
    phone: '555-666-7777',
    address: '789 IT Rd, City, State, 88990, United States',
    notes: 'Meeting set for next week',
  },
  {
    id: 'item-009',
    title: 'Demo Presentation',
    description: 'Cloud Migration Proposal RFP#: TX-1718-Y2022',
    startDate: '2024-12-01T13:00:00',
    endDate: '2024-12-04T15:00:00',
    status: 'Not Started',
    progress: '20.00%',
    publishedBy: 'Project Coordinator',
    category: 'Event',
    priority: 'Low',
    contact: 'Sales Team',
    email: 'sales@company.com',
    phone: '444-555-6666',
    address: '333 Sales St, City, State, 99887, United States',
    notes: 'Pending demo date confirmation',
  },
  {
    id: 'item-010',
    title: 'Wrap-up Session',
    description: 'Data Center Renovation RFP#: TX-1516-Y2022',
    startDate: '2024-12-05T11:00:00',
    endDate: '2024-12-07T12:00:00',
    status: 'Not Started',
    progress: '10.00%',
    publishedBy: 'Manager Role',
    category: 'Task',
    priority: 'High',
    contact: 'Data Center Team',
    email: 'datacenter.team@company.com',
    phone: '555-777-8888',
    address: '222 Data Center Dr, City, State, 55778, United States',
    notes: 'Wrap-up session pending',
  },
];



export const InstallerMockData = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    mobile: '1234567890',
    role: 'Administrator',
    editActualHrsOnAllResources: 'Yes',
    inactive: 'No',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    mobile: '9876543210',
    role: 'Manager',
    editActualHrsOnAllResources: 'No',
    inactive: 'No',
  },
  {
    name: 'Alex Johnson',
    email: 'alex.johnson@example.com',
    mobile: '5551234567',
    role: 'Developer',
    editActualHrsOnAllResources: 'Yes',
    inactive: 'Yes',
  },
  {
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    mobile: '4449876543',
    role: 'Administrator',
    editActualHrsOnAllResources: 'Yes',
    inactive: 'No',
  },
  {
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    mobile: '3334567899',
    role: 'Tester',
    editActualHrsOnAllResources: 'No',
    inactive: 'Yes',
  },
  {
    name: 'Sarah Wilson',
    email: 'sarah.wilson@example.com',
    mobile: '2221237894',
    role: 'Developer',
    editActualHrsOnAllResources: 'Yes',
    inactive: 'No',
  },
  {
    name: 'Chris Taylor',
    email: 'chris.taylor@example.com',
    mobile: '1119876542',
    role: 'Analyst',
    editActualHrsOnAllResources: 'No',
    inactive: 'No',
  },
  {
    name: 'Laura Miller',
    email: 'laura.miller@example.com',
    mobile: '6667891234',
    role: 'Manager',
    editActualHrsOnAllResources: 'Yes',
    inactive: 'No',
  },
  {
    name: 'David Clark',
    email: 'david.clark@example.com',
    mobile: '7776543218',
    role: 'Tester',
    editActualHrsOnAllResources: 'No',
    inactive: 'Yes',
  },
  {
    name: 'Megan Lewis',
    email: 'megan.lewis@example.com',
    mobile: '8883219876',
    role: 'Developer',
    editActualHrsOnAllResources: 'Yes',
    inactive: 'No',
  },
];

